name: Publish NPM

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'yarn'

      - run: yarn --frozen-lockfile

      - run: yarn lerna run build

      - run: echo //registry.npmjs.org/:_authToken=${NPM_ACCESS_TOKEN} > .npmrc
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}

      - name: Publish to NPM
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
        run: yarn lerna publish from-package -y --no-push --no-verify-access